---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: 16.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ## set stopAll to "true" if you do not want to use blocky
    # and/or disable its service
    global:
      stopAll: false
    service:
      dns:
        externalTrafficPolicy: Local
        loadBalancerIP: ${BLOCKY_IP}
        type: LoadBalancer
    # -- set blocking settings using Lists
    # Primarily designed for inclusion in the TrueNAS SCALE GUI
    blocking:
      # -- Sets the blocktype
      blockType: zeroIP
      # -- Sets the block ttl
      blockTTL: 6h
      # -- Sets the block refreshPeriod
      refreshPeriod: 4h
      # -- Sets the block download timeout
      downloadTimeout: 60s
      # -- Sets the block download attempt count
      downloadAttempts: 3
      # -- Sets the block download cooldown
      downloadCooldown: 2s
      # -- Set to fail start of lists cannot be downloaded
      failStartOnListError: false
      # -- Sets how many list-groups can be processed at the same time
      processingConcurrency: 4
      # --  Add blocky whitelists
      whitelist: []
      #  - name: ads
      #    lists:
      #      - https://someurl.com/list.txt
      #      - /somefile.txt

      # -- Blocky blacklists
      blacklist:
      - name: ads
        lists:
          - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
          - "https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt"
          - "https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt"
          - "https://v.firebog.net/hosts/AdguardDNS.txt"
      - name: adult
        lists:
          - "https://raw.githubusercontent.com/mhhakim/pihole-blocklist/master/porn.txt"

      # -- Blocky clientGroupsBlock
      clientGroupsBlock:
      - name: default
        groups:
          - ads

    customDNS:
      customTTL: 1h
      filterUnmappedTypes: true
      rewrite: []
      # - in: something.com
      #   out: somethingelse.com
      mapping:
      - domain: fritzbox.leiderfischer.de
        dnsserver: 192.168.11.1
      - domain: video.fritz.box
        dnsserver: 192.168.11.77
      - domain: argocd.leiderfischer.de
        dnsserver: 192.168.11.211

    # -- set conditional settings
    conditional:
      mapping:
      - domain: fritz.box
        dnsserver: 192.168.11.1

    k8sgateway:
      # -- list of processed domains
      domains:
      - domain: "${DOMAIN_0}"
    #   #   # -- Optional configuration option for DNS01 challenge that will redirect all acme
    #   #   # challenge requests to external cloud domain (e.g. managed by cert-manager)
    #   #   # See: https://cert-manager.io/docs/configuration/acme/dns01/
        dnsChallenge:
          enabled: true
          domain: dns01.clouddns.com

    #   forward:
    #     enabled: false
    #     primary: dns://192.168.11.1
    #     secondary: tls://1.0.0.1
    #     options:
    #       - name: tls_servername
    #         value: cloudflare-dns.com

    # CANNOT be defined in above yaml section
    queryLog:
      # optional one of: mysql, postgresql, csv, csv-client. If empty, log to console only
      type: ""

    configmap:
      dashboard:
        enabled: true
      datasource:
        enabled: false

    cnpg:
      main:
        enabled: false

    ingress:
      main:
        enabled: true
        hosts:
        - host: blocky.leiderfischer.de
          paths:
          - path: /
            pathType: Prefix
        tls: []
