apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: paperless
    namespace: paperless
spec:
    interval: 15m
    chart:
        spec:
            chart: paperless-ngx
            version: 9.10.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: Europe/Berlin
        credentials:
            extminio:
                accessKey: ENC[AES256_GCM,data:u8mdz3ndxWJ8Sd5mE8ZEmBcVEdY=,iv:/MXWIB15Lx+ID/V0HW6LWFynhhn8Sv/H01l9Tcsnk7c=,tag:8NNeFu4BvoAdVlQHEIZ49Q==,type:str]
                bucket: volsync
                encrKey: ENC[AES256_GCM,data:l2Isq5dIjRHZSF8fb0YPqa/thTjPuGHfG0yBA2AzH/6wZwhjsaVe2o0rFzhogZR+3B9olRJtPTEYS//TSz16cQ==,iv:8I2kemY9j6lqzdm9jEQDwwG7yOdsAFS9PDBbENWkU9w=,tag:vaqZ/nwrIB7Hzvm8wmhtwQ==,type:str]
                secretKey: ENC[AES256_GCM,data:2cG9wqZoXgRTkwgso0RdZ1FuPmJNLmMuFwfoOPRyLb76nf1t+jB3Yg==,iv:M+viqklger5bkgV+BhHNFT69a2iQSQ8voHZDL7MS+DE=,tag:U7bpJFW/vm7ERNePYqGGQw==,type:str]
                type: s3
                url: https://s3.leiderfischer.de
        global:
            fallbackDefaults:
                pvcSize: 1Gi
                vctSize: 1Gi
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            advanced: false
                            env:
                                PAPERLESS_ADMIN_MAIL: ""
                                PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:3JWM,iv:Lb6CdcL1odV5UcgXc9DJWJqejCyFymlbo4dDWFbtP4E=,tag:DLnJso9DjF/CK+lsM4fALQ==,type:str]
                                PAPERLESS_ADMIN_USER: sven
                                PAPERLESS_OCR_LANGUAGE: deu
                                PAPERLESS_OCR_LANGUAGES: deu eng
                                # PAPERLESS_SECRET_KEY:
                                #   secretKeyRef:
                                #     key: PAPERLESS_SECRET_KEY
                                #     name: secrets
                                PAPERLESS_URL: https://dok.leiderfischer.de
                                PAPERLESS_WEBSERVER_WORKERS: 1
        cnpg:
            main:
                backups:
                    credentials: extminio
                    enabled: true
                cluster:
                    instances: 1
                    singleNode: true
                    storage:
                        size: 10Gi
                    walStorage:
                        size: 2Gi
                        # recovery:
                        #   credentials: extminio
        persistence:
            data:
                size: ENC[AES256_GCM,data:xxjupA==,iv:wtcaHZm7GbLJAbpFegXazTayDXHnhCmN1byL9P6WgBk=,tag:6LG+UW0ejiUchlDu0rUxDg==,type:str]
                volsync:
                    - credentials: ENC[AES256_GCM,data:zg4rMbUiL8w=,iv:8AcNVmFfOI2E+VcL54xSP6PuOElPHeq/O7SzLuzu5RU=,tag:xDYxtxxmGBtnsJxNBou3Dw==,type:str]
                      dest:
                        enabled: ENC[AES256_GCM,data:6Wvayw==,iv:/5uYyJF2OkuQ212KVNZSxd62LxGWkiqqu46rvANyN+k=,tag:WYpGBY75BDk9WT4wjY6TyA==,type:bool]
                      name: ENC[AES256_GCM,data:Jk5UK7QL,iv:eluetkU98+REa2l6uRVc+HeOTx1k9grmgyb7XpLUOG4=,tag:YhAGit5itALFEj0+zRjTJg==,type:str]
                      src:
                        enabled: ENC[AES256_GCM,data:I75G0w==,iv:7flUZJNuX36wzFvRrqNatP5kYiVzZEh/5sX0fH2POig=,tag:FYBdhk7IBvusQYLGgyLUNQ==,type:bool]
                      trigger:
                        schedule: ENC[AES256_GCM,data:a7QfZCsOgHFO,iv:6nxs5l3NzgctJBBuhvaRQ64G/XKFx+NNs9nh3FmDLlM=,tag:BBx/Kbw99YyLKWOLAzt1mg==,type:str]
                      type: ENC[AES256_GCM,data:SL4Bbiy5,iv:VFIiCwyZzjWchI4cq32O2TEa70LsjCpw9ipkhYA8ayA=,tag:0BFVaoDltD1CfuhhnvPnjA==,type:str]
            media:
                size: 10Gi
                volsync:
                    - credentials: extminio
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      trigger:
                        schedule: 0 0 * * *
                      type: restic
        ingress:
            main:
                enabled: true
                hosts:
                    - host: dok.leiderfischer.de
                      paths:
                        - path: /
                          pathType: Prefix
                tls: []
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zq9rvzhq3suqyxfpr25ak582jyzvv4r6ahlxry0l24k4f7mp655qm5cuk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RCsydDYydk9nZ2xhNjZG
            Qlo3OHU5SG5iMXcvcFh2UHpaSHdkb0NNUUVrCnVpeldCT1pXU3lLN1Q3WEFqKzhT
            Q2ExNzFRa3Nyd2NxYW80cGJzWXFBMjgKLS0tIHZDVGVlekFJWjNaZmlsbDNMaTl2
            a05keGJHbjNadk1DbUNXRHRDcXdURG8KGzokU3hHO22sAbEfKnNkUGR1A5H64k7D
            BpCeGOvPpShnn83UlVWPkATKcZNDiz5g8vafaTE8nwlxu7Nukp6woA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-02T22:55:32Z"
    mac: ENC[AES256_GCM,data:kww86tS06Sn/EayYS4yMlhqBqZioBc/04R8EaC3pPXz/6IXDOg5cqvy8mVsPNf30aZMIxNKQWfJiiachLmIfs6SeRA5EcWNVkPWFVKNr9+/I0Dc7Kj10SDTy2kF+umwo73qTFBVfSpjHNHtd1rsAgS3BLh7SFm3kSZCkLwVpU00=,iv:UPyAAcTQ+EvK4j8nmb1WHul5/ajEH6ukm1EcLy2Gt8U=,tag:MIZVaPPyN+CYRkbRZbKvtw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
