apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: paperless
    namespace: paperless
spec:
    interval: 15m
    chart:
        spec:
            chart: paperless-ngx
            version: '>=9.10.8'
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: Europe/Berlin
        credentials:
            extminio:
                accessKey: ENC[AES256_GCM,data:9vXpkkS2ywRrGcPPCrzWleHmpoM=,iv:RgYhxxYvkvnPC8WYAhp5C9bhVzdMZVX23N8INEMDAU0=,tag:P/1jQPZSkVsZBagnqw+O3Q==,type:str]
                bucket: volsync
                encrKey: ENC[AES256_GCM,data:ji3huw78dp3WJGSDUsZkg2MINnyCBh9uxSdFhGqt45jPvDoKnkHCgWUZcszCtLSbwUoSRkxnTlTDgGKXILENgg==,iv:E+zGP8TCVQ41Yo4vhzDUaGzlcelQrlRhcKQi+TLxCWQ=,tag:Jgv1qrUTC+p2P+4UTwsnwg==,type:str]
                secretKey: ENC[AES256_GCM,data:9DQrdsYJD8hln6aRFWdayZTCDkfevXgsGtxlh1mQ0JILwjB38X3hIA==,iv:PUfmHuX4bB+/MdPEt/dGV1Ie9nVGM8+i9nM9yx8VGI0=,tag:rZeQl8/B3kdK8L3f75uWUQ==,type:str]
                type: s3
                url: https://s3.leiderfischer.de
        global:
            fallbackDefaults:
                pvcSize: 1Gi
                vctSize: 1Gi
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            advanced: false
                            env:
                                PAPERLESS_ADMIN_MAIL: ""
                                PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:9sN3,iv:dPLDBKofiNwrGAxZLcfGYjtUOAY+dnBUxyMUIEw+sok=,tag:9f0JeEVQyeskJXUTxD3d6A==,type:str]
                                PAPERLESS_ADMIN_USER: sven
                                PAPERLESS_OCR_LANGUAGE: deu
                                PAPERLESS_OCR_LANGUAGES: deu eng
                                # PAPERLESS_SECRET_KEY:
                                #   secretKeyRef:
                                #     key: PAPERLESS_SECRET_KEY
                                #     name: secrets
                                PAPERLESS_URL: https://dok.leiderfischer.de
                                PAPERLESS_WEBSERVER_WORKERS: 1
        cnpg:
            main:
                backups:
                    credentials: extminio
                    enabled: true
                cluster:
                    instances: 1
                    singleNode: true
                    storage:
                        size: 10Gi
                    walStorage:
                        size: 2Gi
                        # recovery:
                        #   credentials: extminio
        persistence:
            data:
                size: ENC[AES256_GCM,data:dN32bg==,iv:MqZNLMci0PMewJeDVuMpdl3uHoWnn2jn4RA2LZ6NN6I=,tag:6Ev6d1AVihescqc+OlGCqQ==,type:str]
                volsync:
                    - credentials: ENC[AES256_GCM,data:15zFskK49TI=,iv:rfVWvfNHrYRjGfsy0QAgiMOAH6325ymRvbne5ytd7wY=,tag:Cy6R2iK1PgbIZvLJzbQGBg==,type:str]
                      dest:
                        enabled: ENC[AES256_GCM,data:DTXjAQ==,iv:3uOtSYuF2l2pQ7JyqwOol7FM54UZZPB9uTIOLlUw3NQ=,tag:Z8heGwubsC63zkcfPQaa8A==,type:bool]
                      name: ENC[AES256_GCM,data:2Br5YOl6,iv:DkYMmPig2n/upvyfS++rGSYJHzsBoZhPKxbYgOMxanE=,tag:JtFkA7jXahuOkPC5EKYtuA==,type:str]
                      src:
                        enabled: ENC[AES256_GCM,data:w7ssNA==,iv:+zeALF1N4pY6b6RPN8fsVo6cVxRq4MjSg0FE+JqMpCk=,tag:GfzIUEZ+VZuw4EvKv1nIag==,type:bool]
                      trigger:
                        schedule: ENC[AES256_GCM,data:zLRu5t8lLfFi,iv:PLpxEhdKzsx4vOXtF0WnsHc8hxQMRpkYweaXYju/ZeQ=,tag:jeZsrxbY7HsS1qaWi/9NJQ==,type:str]
                      type: ENC[AES256_GCM,data:8TUuU2qH,iv:ldQgUzD436XzC4ZItogEemLM96zZ49WmH4zwb02y7eE=,tag:YaN41lyd4gdRjRdE8/FCPQ==,type:str]
            media:
                size: 10Gi
                volsync:
                    - credentials: extminio
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      trigger:
                        schedule: 0 0 * * *
                      type: restic
        ingress:
            main:
                enabled: true
                hosts:
                    - host: dok.leiderfischer.de
                      paths:
                        - path: /
                          pathType: Prefix
                tls: []
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zq9rvzhq3suqyxfpr25ak582jyzvv4r6ahlxry0l24k4f7mp655qm5cuk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMEdwYTJIQktpbEhJZFF0
            SXBaa21KNjdnbVpHNzllTElQZGVGWEFjWlNBCmpHQkVjK3BZSWlpN25ySEZMdEJZ
            WVpGLy9JSjJUVjRPRWwyRm13M0FIeGsKLS0tIHJJTEU3TFM5UnVtclJvV0lqZEhG
            b1oxeFdtRWVkUFFHTlZVT2lHYnRwUmcKpwNidWQU9k7sYFpOJOCUFk8/OegT6crA
            /hUGzZ7GHCstaOEdyiAwBq+ELqh91ZEFqBCmmcfXZwF1ZuOCP1OrpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T13:10:04Z"
    mac: ENC[AES256_GCM,data:VZO335IVxEtIZxcN5IKa7bnQ7O3CA+5EdKO7EoioL4uXyTldAwGWWlwsulNsfnXDKSSstV3Pfn3YuyHHiFGHo6jh+/zZdb/LmdZ8Rwvr/YECND1h7pZZjgtOVdiWiKlAR87tw4HzU2eisc/1MEyvYtOMq4oVKK2/CiWbO/8tCWU=,iv:x0Fzob6DQxM/0OxGIabScLQpc/UoP0MniQdXw1RDOD0=,tag:OHUDcrr8tGUyampjW2FZWA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
