apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: paperless
    namespace: paperless
spec:
    interval: 15m
    chart:
        spec:
            chart: paperless-ngx
            version: 9.10.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: Europe/Berlin
        credentials:
            extminio:
                accessKey: ENC[AES256_GCM,data:pfPK1mR9R2+3P5G61JR0oEK5uCs=,iv:R7cEGDJsrF2ywFgiygdf8lU1mepEA3tI5HH/qwTKsCY=,tag:KAGVx8PeM4lrFI01iFmccg==,type:str]
                bucket: volsync
                encrKey: ENC[AES256_GCM,data:QaMXRSGu4iCG/5Vs+X0rpdxnwsTxdYcjjME718C9gChQ6gL0P+oEzSvX/+uo+cyC4jKP2wD6x1cd6I0Jn1CJxg==,iv:w7cPJPE9WofiaAW8kwpTH5TvvWOWECTqLqKgh5r4mLc=,tag:KcdTa8A7pRjms1sgZJPKWw==,type:str]
                secretKey: ENC[AES256_GCM,data:2s/w6oxDqfRV9zEU3GkOQLYxGkPbmieYgvjWxqzr6ZqfCByLqdIBPw==,iv:NmK/96nVnxlaiT441Jw/qToKnfha1zzYdRTh7lFY2zY=,tag:yMd4S66096+rZQA22VtbIw==,type:str]
                type: s3
                url: https://s3.leiderfischer.de
        global:
            fallbackDefaults:
                pvcSize: 1Gi
                vctSize: 1Gi
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            advanced: false
                            env:
                                PAPERLESS_ADMIN_MAIL: ""
                                PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:43PN,iv:yLxKB5TpQo3N2sGOD3qnlCTpSXZ+j4kSKY2RzRfbNlM=,tag:pjWtg50t47di9PhRey8Uig==,type:str]
                                PAPERLESS_ADMIN_USER: sven
                                PAPERLESS_OCR_LANGUAGE: deu
                                PAPERLESS_OCR_LANGUAGES: deu eng
                                # PAPERLESS_SECRET_KEY:
                                #   secretKeyRef:
                                #     key: PAPERLESS_SECRET_KEY
                                #     name: secrets
                                PAPERLESS_URL: https://dok.leiderfischer.de
                                PAPERLESS_WEBSERVER_WORKERS: 1
        cnpg:
            main:
                backups:
                    credentials: extminio
                    enabled: true
                cluster:
                    instances: 1
                    singleNode: true
                    storage:
                        size: 10Gi
                    wal_storage:
                        size: 2Gi
                # recovery:
                #   credentials: extminio
        persistence:
            data:
                size: ENC[AES256_GCM,data:0AmXIA==,iv:lVX79//U2FFgHmHu4vR325QJr4edRTPtcLc8wM9A5DA=,tag:mYthnMigVBaFP4rFfYJJ9w==,type:str]
                volsync:
                    - credentials: ENC[AES256_GCM,data:8SFbLrNf0UM=,iv:OOLmdELZ11/1Mh4eh0y0FdpG5PlLIWH1qLd1WWqi3+g=,tag:Q8mzSJEMS3FcoJuOwVFnOA==,type:str]
                      dest:
                        enabled: ENC[AES256_GCM,data:sD7Avg==,iv:Q0Bmx3PI5EvoG58Rdpp2k4MlfcwZnKHU77Y+cqUTBoM=,tag:Qi8LHkhUWa/dJPrdK+OKeQ==,type:bool]
                      name: ENC[AES256_GCM,data:xt/amEjz,iv:1iDUmFVpCoKoLN9ZAv37OM0t7cKhR6S9TmRVh4yXksQ=,tag:AII3CnW4Ay44M4Aim/vY7w==,type:str]
                      src:
                        enabled: ENC[AES256_GCM,data:6QHrfA==,iv:UI+GOuc5rkqZIp0pz6DMp1MjefBmYmHYjNG4EbKbeFY=,tag:AAqLNkFSOw0w5uzApgxkyg==,type:bool]
                      trigger:
                        schedule: ENC[AES256_GCM,data:24xASCuG8vX7,iv:kWVn2bIG+IBDd9/Oxv12mQnzOrKh96nnTW5BEAcxiIU=,tag:1SeU3IgV+D1MPBjS0LcIWQ==,type:str]
                      type: ENC[AES256_GCM,data:7pjGH5lb,iv:gAxLdWSRybDioIYhxWddlHWCm5VCXZNQIITLPtjoQj4=,tag:2njeJeH7KZi5lvl406rMMA==,type:str]
            media:
                size: 10Gi
                volsync:
                    - credentials: extminio
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      trigger:
                        schedule: 0 0 * * *
                      type: restic
        ingress:
            main:
                enabled: true
                hosts:
                    - host: dok.leiderfischer.de
                      paths:
                        - path: /
                          pathType: Prefix
                tls: []
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zq9rvzhq3suqyxfpr25ak582jyzvv4r6ahlxry0l24k4f7mp655qm5cuk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWGRveEdlWXk1M3h4TVNw
            b2lCd05wL2FZNFVLc3FmQVFqeDVNeDNGbkJJCnJLM0IvUFNkTFI1akRlMy9TVVlZ
            YTBRa2hwczNNRlpOZFhGM0t1eThtaTQKLS0tICs4S28xalV4ci82Q05iMWloZkoy
            Z1NjRzlYdlhZMXF5NzdqWXdjcWE2amsK4lDCHdhJP4GjTiNkhgRiGIryzQNFvY+l
            sCpEirb6CcyZL9QPRNrtRF1xpHwXBD2NJoZqRv97cDpzeHkp3YuCnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T17:13:19Z"
    mac: ENC[AES256_GCM,data:Dqqs2nMY/KJeUDZpWo+yw3Q8IAmQOjt7dp3zYIrabsLZaFT2ynt+p4ztLpnWmlCEEbUO/tZvAQ+e3VR8rmiL3qz3q6SgW6q6jL6Fzri+u9AYVt8cO/e4aSqsQ5KNey60ZO7RIsi7wbZS0HUlrObmY+dmmuH4ExmxaS0ZsuKhsN0=,iv:wJzxnbrlfStmjVqw9dSlovnknyzXRrGkuBo3JvwAHHQ=,tag:wAHPJ4KquTxg692U5gABcQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
