apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pgadmin
    namespace: pgadmin
spec:
    interval: 15m
    chart:
        spec:
            chart: pgadmin
            version: 17.x
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        global:
            fallbackDefaults:
                pvcSize: 1Gi
                vctSize: 1Gi
        credentials:
            backblaze:
                type: s3
                url: https://s3.eu-central-003.backblazeb2.com
                bucket: svenihoney-backup
                accessKey: ENC[AES256_GCM,data:daZbJ7Oy9gsA3VEMjQLaKl9pBYdHBOGO1g==,iv:zEBTcRXXrjn774yUwq+9k0X47AxkolUzQN1xU2ItKoM=,tag:6bzXv0NpTSD2/NkPei84eg==,type:str]
                secretKey: ENC[AES256_GCM,data:BpdOTzLLhARUWD+ADrov+EPRZMPGX9jJjnKGJrVXpQ==,iv:vp78JnrMsY6hPuR//cGhjNRooAci2dDDB9YEAQzE+KI=,tag:15piCpLxEcuIFP8FSwA9zQ==,type:str]
                encrKey: ENC[AES256_GCM,data:2SegfytJHIjrMxfU5SF2KmppG9I=,iv:Af+bn0D8fTDoVLC0tfC0K9H2n5N6IOscfHqqLgIGQGA=,tag:dlQFCwlNeg+zpfp+fDyl8A==,type:str]
        ingress:
            main:
                enabled: true
                hosts:
                    - host: pgadmin.leiderfischer.de
                      paths:
                        - path: /
                          pathType: Prefix
                tls: []
        persistence:
            config:
                volsync:
                    - name: pgadmin-backup
                      ## TODO: other options
                      type: restic
                      credentials: backblaze
                      dest:
                        enabled: true
                      src:
                        enabled: true
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zq9rvzhq3suqyxfpr25ak582jyzvv4r6ahlxry0l24k4f7mp655qm5cuk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMTBUUFNRSHVEMHJ6bjZZ
            QXVNeUNFS0p5UXBkUVRTeFJhNWZ4Q2pMeUhjCkNEL2toZDVhYVV2YjZUTkgvRWVC
            Y3Z3T0E4a29jVDlOT1dXUEJvcmQ3TXMKLS0tIHZzOHNTdHZETmpybmViaGZjK1dn
            eUg0Nmx3M3NOTUZiZWV3ZjhMVC9XelUK+UUXu9rc7mO1oGSFRDq6n091sMq6RKcT
            pGAdk7JxwLK/ASV3FsZBFiOiuaFe6mPwL9NiSeQg9XqbvpBY6LafmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T23:17:45Z"
    mac: ENC[AES256_GCM,data:zFTKgayrVVuG5VhPIqlXrmxt72wpN9cDOUtDiDYabOWwrmPK5vRPY6Bt+HU4XtDMo5eYeBqeIjUy+/t98RoiDpzAO6Jz/vEoCtoeRIgYpV5TtEjVGWoFffo7SAGggbZ8bPcp7UKvcfLsFsyjfXogRtkZeVcfSL4VAomBmTvq88A=,iv:uEa4E7PcinXzBZHCZxFLGSLAPuMps5bZAXJP+IlHH5E=,tag:0s7pBaXJ912uSy9/5DI+XA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
