apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pgadmin
    namespace: pgadmin
spec:
    interval: 15m
    chart:
        spec:
            chart: pgadmin
            version: 17.8.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        global:
            fallbackDefaults:
                pvcSize: 1Gi
                vctSize: 1Gi
        credentials:
            backblaze:
                type: s3
                url: https://s3.eu-central-003.backblazeb2.com
                bucket: svenihoney-backup/pgadmin
                accessKey: ENC[AES256_GCM,data:6j4m1lAfvjvwEphuXrZ2SXBz9p9tah36AA==,iv:u/glcvpMcuSavmVSWfrbKSs3kQS4AYVJEVdANDUNEYk=,tag:MNdkd6bY7KY4hbPe1jj9rw==,type:str]
                secretKey: ENC[AES256_GCM,data:etU95gX6xUPcDTArfTNgulT54mkrcfdQ9dHUgWWXzQ==,iv:nWNp+RF1z5QV/QBlM35g/NFinre/WMh70QEHWnwbgOA=,tag:0fCwLe8MtlKebW7cbuwfbA==,type:str]
                encrKey: ENC[AES256_GCM,data:SBt+fOehX6J7+0BeYtSBB1q5duQ=,iv:XJ3pag02wFOi9BfcFyrNTXWLlHxkR9ZjGqnK1f6Fsr8=,tag:SHophVyGTTp3zZR3NDPTyQ==,type:str]
        ingress:
            main:
                enabled: true
                hosts:
                    - host: pgadmin.leiderfischer.de
                      paths:
                        - path: /
                          pathType: Prefix
                tls: []
        persistence:
            config:
                volsync:
                    - name: pgadmin-backup
                      ## TODO: other options
                      type: restic
                      credentials: backblaze
                      dest:
                        enabled: true
                      src:
                        enabled: true
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zq9rvzhq3suqyxfpr25ak582jyzvv4r6ahlxry0l24k4f7mp655qm5cuk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMXcvb3lTNlNyNGdrME03
            aGxJaXR3OFRkUDVyeW5GMzJ4aGl6VWlScjBZCi9hOXd5WnJDQjRrYnNhRzdEY29v
            QjVPdklyZCtTMlo0NjYvdCtjeko3dTQKLS0tIGlrZlAvOHFoemRjYTU0ZEJtMUF5
            YTVnMjFsRkZ2V1FRVHRBZ3FxdDB6aUkKZ81s6pGGAZ529Lw6GCj1xZ+L+CwhPVo8
            0lSwo8o4zBbKUzZ5jOIPB54vpYW1DMvsMXZ7M4ZR5eX+i6JuuvDDMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T16:41:48Z"
    mac: ENC[AES256_GCM,data:canS+yqR+19yAXD3HfBBwyztzYH6UTl5iVxOO14IZu1bO5uvzzQU5RCc1vix6HZnIYL7dGQL15tbDjEfWZuYuX3Pp4t9h5UHJ4kAB9vxvqC7dAyJ41loo6z/yeXXbRHaacYKhFQjYENcaTcbg7GsxQ73iwuVDVG0dAMY3s5zQN0=,iv:6asMh9Vjd8IdNykR3IInwNryaENsubv4Kmv2u9ypCDM=,tag:AjofhdaJqaE3CHswicsm8w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
