apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pgadmin
    namespace: pgadmin
spec:
    interval: 15m
    chart:
        spec:
            chart: pgadmin
            version: 17.x
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        global:
            fallbackDefaults:
                pvcSize: 1Gi
                vctSize: 1Gi
        credentials:
            backblaze:
                type: s3
                # url: https://s3.eu-central-003.backblazeb2.com
                url: https://s3.leiderfischer.de
                bucket: volsync
                accessKey: ENC[AES256_GCM,data:v/TQ31UEL+jSutuWP4Eqe2TnzVU=,iv:FP0fYFSihKs/bCHX/VQV//A7PUBaChgXKtnTEpIPvZk=,tag:/jBTtvElWTasDz7BQ/MZNQ==,type:str]
                secretKey: ENC[AES256_GCM,data:HwTGgJyGAUxFnyg/8zcmb0pOayHcLPfq5pd9R6bju7YHEOiQ91O0Cg==,iv:HRxUUKBXqxNmK8aRUTOm9ngM2FASg9GegcVWE3HOTzE=,tag:Bv3hqXFt8usBDUUK/6fZzQ==,type:str]
                encrKey: ENC[AES256_GCM,data:iTeWUf5xvUuBwkgdnE9DJv5McurMh8+DcoKnvys+IEP8dsHILMEszzxbY1/xvNMURW977qT0qwfQFPV6yzsP2g==,iv:Xa/cav0aRhWctd9xudo7afBDObplX0GeJq9rsfHwUCw=,tag:UwUxy799soLKz3ShOX81zw==,type:str]
        ingress:
            main:
                enabled: true
                hosts:
                    - host: pgadmin.leiderfischer.de
                      paths:
                        - path: /
                          pathType: Prefix
                tls: []
        persistence:
            config:
                volsync:
                    - name: pgadmin-backup
                      trigger:
                        schedule: 0 0 * * *
                      ## TODO: other options
                      type: restic
                      credentials: backblaze
                      dest:
                        enabled: true
                      src:
                        enabled: true
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zq9rvzhq3suqyxfpr25ak582jyzvv4r6ahlxry0l24k4f7mp655qm5cuk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZzNoNUpqZUtYUTdCenV3
            NGpjVzhoWEQraTVONjUycVhFbUdUYmVsUDB3CkM1N3Y1LzN1UFRaNUMybE1rYzgz
            enQxRGtjMzlIa0NIVjdvN0JwYWFyNE0KLS0tIFBRcjA4bXZWS2V3S2R6cE45c3lG
            eFFJa1R3UEtCYUFCOTBETVoyYlp0VzgKihBn5NqQuuBNaVq/GjPrcBUOXAVTrPsg
            WkVKK/CE6y1WtKr8ZD87sV2PpSyVt4ztJ6rYFD+dCflCSSWf4Ghwyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T22:13:23Z"
    mac: ENC[AES256_GCM,data:yVW5GrSGddH/+8brzCNRSZPWYEAvKFjkEyqCHEIZagLUucAE4noH9GamzwDPyoTAWqvgYHJvTtdolf3okgBClPGKjntir7exczs6Qcxj2jXp9gNhwyntrrJNiov31mhKIcH7N1k7+17UQi9HoHF1bjjXSOVjJ6Hpa5cQjOBI+XM=,iv:9fLNTzWl4bO3rdQpkVtcsKrrZH7M5NZBviL3oMIww8g=,tag:Z4YLgCFJCXklfIkDKkE3mQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
