# Restic-config Secret for pvc-b
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-pgadmin
type: Opaque
stringData:
    #ENC[AES256_GCM,data:po1nolLzBfgGgYnhsRfolmRAj1iCIiFUdCVVKm+/3IChJWZe1ptAlo0m8GAhgAZkYfym+C3p+DtcD78tbdfZ8/+7ww+jQ2LYEgFEPds17vIZ,iv:HLcQ4sVSW4YP55EA+QCjs58tIn+QEYEXQpaKmmMqXWo=,tag:AQdGsEUJ5KKYTm417q2PLA==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Di0eyUnK1jzngDlpJABK8YXpyEqo5et0ngIg3eB0xRAUNyouV1RCAaONUkxznX/HWD5X7Fn+pOZqanwsQM9Rf+3ziLmWlQ==,iv:OnJpND65rFk1KfLxVos/t1jdtBZV+ghsNXzT2Qy8x9k=,tag:ZasxHgpUJPN5vrFy1bk01w==,type:str]
    #ENC[AES256_GCM,data:Zr38KpRgoBIIK6qY5oQj7RVZ4gOZ6lOk32oe00TEa4qy+fp6iJ+XlxWyAkS69naSQyCdVDtY01SZvsgTM5n+unBc8pK9HsaBoIj01n3hk4JJaCR8pP8XkBjGpiZ6epqBAdiP/w==,iv:JBFBr/5Vy2gBFxEcWM1UID8YtV5CbCYEK1tWJmjHfNo=,tag:5ulOSyTDGJyLBalgVYt4qA==,type:comment]
    #ENC[AES256_GCM,data:CD8ujE1rOCPB/s1Dz3Wh25ry0xJDn3VH2hIULyAqZ74cFROtyPcUjt+eybdZXD509M7p7lO5U+Ey+XFs1U3phDAQTAi11yxfJ0cR9AEdqSMnXTEmBWYJcqBRY4S27tw=,iv:A06HuIpa5dAU6UrV9YhSS6vKF8xmev4WIO4uZyuHKqA=,tag:xtI/krIFCaG+3PMgixjYwQ==,type:comment]
    #ENC[AES256_GCM,data:1yQKR/8ZBy4ESqD+Sjt+SGuur+Z41tYKiKZQ0CJtEc63UldLQOunSr8jlcuDCKN8DbnpS2/6fz6gVzl8R2dOoulaz0BA5CqO8ftOGRtZhpGtvuXNxg==,iv:0X6N6rCi+8ArzoRl9NhobZsVHpCOrYW33ghc8PvKaG8=,tag:6Le1gP5w7+o6rD0nrg1v2w==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:dDhKQzFg,iv:mhd6FwhHKY8PjvWuYZFImiie4Be6/GnDNA0E2B2ThdY=,tag:6a0Wd1kqFQJGMkCbQ0cKQw==,type:str]
    #ENC[AES256_GCM,data:bPJoRfdwRAqoyYFQV92mPNJu1R8rt+Oh57dmlA8azIv8CQ==,iv:+8TlqcDCj2e3ORfAwimil0pi6Oz3TZDO5ucWWMwJFdU=,tag:KSitKuh6nsq30DQRUloAuw==,type:comment]
    #ENC[AES256_GCM,data:ugX+FfyI4vgodbFALESdiRJ8xdVg1BKDAPn9y+cep8x8QejpS1kv4pLrrcWxZP/ru8KFKgecKy+8PGHvfB8S2rVoJXqyiw==,iv:AC/Sgp0myZ4Vo5aeJwd2cObcHJJaZpRyBIE1NRWDN0o=,tag:m/iyoxo3KiT0C7N/LM45uw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:BB3ZFaXTIA9bRi0y9/mWu8h/fLNezdNZrQ==,iv:UdXXwZAq9lh2QlNDo3h2ffwatbwXobeUTzHLYNAEh1M=,tag:10MQvZBp3WFv2q//0kwhAw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+eVIQL7jKKQ3TZ8yFK/ZWL2Ao9XomgTLcqS3mCnsAA==,iv:UUcUbSVJLRhILv/iMrTtE56GQBX6k8pQx2ib4mnwoyU=,tag:P5ippWV0XoDFj5GIHUqamg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zq9rvzhq3suqyxfpr25ak582jyzvv4r6ahlxry0l24k4f7mp655qm5cuk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYnh0dFpjbmhOVTBTTlUr
            MlUxYzVmR3hNckkyYS9YUXVOOVRpNDRFejNFCkVXblFDL1d3L0hWeVdQNll5M2dZ
            cU8vL25vMGYwR2NsMUdHUDVnZFFCdnMKLS0tIGtKN1lod1dMQWprTGUvdk15bkUz
            cVJHODlaRnlnSE5TYzZkdmhwV0g1SkkK4vTrFfdhJZ4hCjTCPkWqOAEds6eLbje5
            d31OwjY3LGh5mGR2SdnUsv52bjgOCObLjUt+JyOA90NRxyPZdxvIvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T12:03:06Z"
    mac: ENC[AES256_GCM,data:GQyqnXq4/IuAstHxMOB1q/lwUNlUwmE2+Qs+gDLTxKEYxYI0fSAQauEsTXxpASZFzNnfM/4q+v3Ze/im6WwovvsJ7CiDcNj8IGtgK0zT0hr59mOC7qdtk/xJqZq2ZM2iUC/0LOOlhRaT5rtmtQz5BXj+hSX1WDnC7DbrHe6uONY=,iv:BTOJY7wTQmGvkcuuPHcm/iE/mtaMrO1jxKqeke73uPA=,tag:jMQ8RmanZuBLtaQZiogpCA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
