init:
  # Clone/copy method.
  # git, wget, s3
  method: git
  # git options
  git:
    # The repository to clone
    repository: "https://git.effeffcee.de/sven/party100.git"
    # The reference of the repository to clone
    ref: "main"
    # Sub Path of repository to copy if not root
    subPath: "/"

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: party100.leiderfischer.de
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
