---
apiVersion: v1
kind: Service
metadata:
  name: mx1-ingress-svc
  namespace: traefik
spec:
  externalName: mx1.effeffcee.de
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mx1-ingress
  namespace: traefik
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`mx1.effeffcee.de`,`autoconfig.effeffcee.de`,`autoconfig.leiderfischer.de`,`autodiscover.effeffcee.de`,`autodiscover.leiderfischer.de`)
    services:
    - kind: Service
      name: mx1-ingress-svc
      namespace: backend
      passHostHeader: true
      port: 8443
      scheme: https
  tls:
    domains:
    - main: '*.effeffcee.de'
      sans:
      - '*.leiderfischer.de'
