---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor
  namespace: tandoor
spec:
  interval: 15m
  chart:
    spec:
      chart: tandoor-recipes
      version: ">=18.5.2"
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      fallbackDefaults:
        pvcSize: 100Gi
        vctSize: 100Gi
    cnpg:
      main:
        cluster:
          instances: 1
          singleNode: true
        pooler:
          instances: 1
    ingress:
      main:
        enabled: true
        hosts:
        - host: kochbuch.leiderfischer.de
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - kochbuch.leiderfischer.de
        integrations:
          traefik:
            enabled: false
    portal:
      open:
        enabled: false
    crd:
      verify:
        enabled: false
    operator:
      verify:
        enabled: false
    workload:
      main:
        replicas: 1
