apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - kubernetes-dashboard/ks.yaml
  # - home-assistant/ks.yaml
  - pgadmin/ks.yaml
  - paperless/ks.yaml
  # - minio/ks.yaml
