apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - helm-release.yaml
  - multus-daemonset-thick.yml
# See https://www.talos.dev/v1.10/kubernetes-guides/network/multus/
patches:
  - path: patch-talos.yaml
