apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml
  - multus-daemonset-thick.yml
  - network-definition.yaml
# See https://www.talos.dev/v1.10/kubernetes-guides/network/multus/
patches:
  - path: patch-talos.yaml
