---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: kube-multus
          volumeMounts:
            - mountPath: /run/netns
              $patch: delete
            - name: host-run-netns
              mountPath: /var/run/netns
              mountPropagation: HostToContainer
      initContainers:
        - name: install-multus-binary
          command:
            - "/usr/src/multus-cni/bin/install_multus"
            - "-d"
            - "/host/opt/cni/bin"
            - "-t"
            - "thick"
      volumes:
        - name: host-run-netns
          hostPath:
            path: /var/run/netns/
