apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:wsQii0T3RsqnQl8M+m3gHIdvqroJJtkj2jaUPXijD7W6cH/92BXckH/PkPzVsWJ429WgcDTi8tTNyQxrilYqiq0=,iv:cxMlS2DIFFHbia2qTBuCXyWBIcZ02olPJyuyeMfKNJ4=,tag:NOPREr5Nq/5wzph6XF3bNg==,type:comment]
    #ENC[AES256_GCM,data:WFBAi1G6JeY3nj8picfJQnNfxKrhEqjWkoLn/uRIJbMfXoElb1Nn1O4CH+Y=,iv:O6HKJAnL6W32Plgc9LDGLe25R0OMTc3YSsWhKfnvV4Q=,tag:ifip05XfYbILHLOGXX4rHQ==,type:comment]
    VIP: ENC[AES256_GCM,data:XTSNbkxu0rWnDc2gkPA=,iv:PGgLL0eOVw/G4JSsvZtG9aFMenG8efjx6+EvbEeMegw=,tag:wvRiGM513y4/wKMVUDW2aQ==,type:str]
    #ENC[AES256_GCM,data:13AL9ib2D5MQE57o+iXornT7ne5qFOwYp5Bw,iv:aSu+WU6NAVV/BYZzH6ZmvzmcvHYHTlZEkGZ5FNUdqls=,tag:KwBLlyzuUzG4igZc5caB3g==,type:comment]
    #ENC[AES256_GCM,data:WjN4zjm/SuNeKNbeJIUb+F5czK7tFoArtkDofdwZNGGjMtVXN3hUxzzE67w9e35cOSd2/YF4yqWJ/4srOLbfTZ07C1ukL5kuMOouwvfUVHTeiLjE6NP53GU=,iv:ZtZEj82vrmKEN5M/4qycOkVqk8z6kW31tKEoxY5Y/gI=,tag:0QaMu58O1/lpw/DCw7Btvg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:bVGJuRSzB4LTKL4Q3/M=,iv:KH18li5aD7uefaX1wUbDRClc1PafCwaoagKpY6kKu3U=,tag:5sSrLVVWOty7JrvCsRKRyw==,type:str]
    #ENC[AES256_GCM,data:lK7+2NxZFQVpmeqC18YYFf/JJ8M8UYrCX/rltFM1o8g7xg==,iv:QW36BLI7+Q/YSjWRH8LYoUY/5HBAW/PGCHAeRwyO+68=,tag:nw3gDEbvfDuBGs9n3Uhy6A==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:EECWwGcRYvs/KaEG,iv:+FdxdUuOi9Px0JG9qU8JO2uEKH/M29oavMJc6QcPIvA=,tag:7/nkIeuqGYTNVEfKl5FOow==,type:str]
    #ENC[AES256_GCM,data:CtszKTlXwT1mvdfVPlY2b3nCFSilU3FVZIfoZCRQ5nurIlpsXok6rcUULCn8qzI=,iv:q4dKXaWVQZwluW+uC0PEtx7aftDrzAztiwN/iQDASqo=,tag:PM+Z/Rn5Z4mZ3TeAgGFwbA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:VU4KNkscwRCNrGScP0ZtbFgog2lVuHfEpQ0/6P8=,iv:DgtHWcJmR4u876UnNeJVtpZPsnbYcq+ukbZxMOpuQmM=,tag:rXo08m7b+BYwBwi2BixxuQ==,type:str]
    #ENC[AES256_GCM,data:TFyVK26fUOsnvrQ1clQetab1r5uzwKSIzvy68y+K7BJs5XGl0niS4N9MRfghKpz3Z7wTK9g69ifYtAF+HI60wQvr5PlRadm+HzTFpwtT9yDwig==,iv:BKFIl+db60g7zKITVQUzmSGaqZiWj+DDy+SJmIdYQ8w=,tag:rvyH5fycFUmev+xzDdvAcA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:ENhHwHILfyy8GD5/UYU=,iv:jZA+xzlm1vaDJ4eC7uYtjUL+r9QJOUtNh0SB9doOCXc=,tag:MSgKnV4++P5CRNVsAesX6Q==,type:str]
    #ENC[AES256_GCM,data:rxaE1D1m6Sdx5kAgo+kNqXkSYpWmDZFFeEA7B98J2iTZ,iv:7dCFJB7++A8evQVU2IkE8GJBenf0M+i06fZq18i7I1o=,tag:vpq6kfzPWwQQadl6tm29YA==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:fx/um+FTITHvuFxudXg=,iv:AIENFal1NgcUREAB/3W0O8xkMtBLuiLeETisbJsUtZo=,tag:R8zv+GZt18PMD6Y2H9lo9A==,type:str]
    #ENC[AES256_GCM,data:eX+BRoyD/H4+6b1Kd0ZucPgt4EOS+rQ5LXFXmd5yx9+RRVSY9WdOcBNu4sAYrpd2+3E0aoI3a/uVMm01hJ/aYw2tNbn87OMPWerjdeOTVzE=,iv:/vZl/sIWr0XO39YnzfjXJsbiGrQ0uRfb5CVynt3oZN0=,tag:NvFGwXm7VXChj8DLJlKsdg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:KzM8GmAEab+2jFZgkYk=,iv:cHhvrklUc+B+m9Fb5nexRbOUIlMsuRZ92bj+HyZ2yZ4=,tag:qwwrxl6slDNoFx97XmO5hw==,type:str]
    #ENC[AES256_GCM,data:Db4Ip2kmNr7/KrvzDn4fCt/jIF5oqxoqCADt6FeMAaznY6W2tC+wnLbt5cR7IilZ7zeTPZGLySKia1y15f+bFoNfcb1ou9hv9tM72racMjnKruuw5gzQ,iv:SaC62yMeogj62FWPfd7jMcQ4GgodUR+YNjdKveVrADU=,tag:bbccM2VghO0q7wk8jXd8NA==,type:comment]
    #ENC[AES256_GCM,data:34HHrF/11xY26EXEzkZZKadAiYNYL2yBMwQHumoZ5Pqv4ub44xA8LMnQ5N8/JnCBnt9GB9kiaIyOahOsvTZEHIiFsJ8d58WLXc0RScq74mTDCcMBYhg5z4lgCItcco8sRnCROeEvqG/LW4sQ9nbueAXlesw8jaH6xpYaow==,iv:SFjedhPljXvcs0YJ6TDfcWK+XOdcDjjYKRsvchAoUsk=,tag:jIlRwX/eFMaLZ+6YXMdruA==,type:comment]
    #ENC[AES256_GCM,data:eprq3uRU/5cy99qjsu/atPP5Dl2moIhfvSNSnB7JNjy6O53bWyKXa7WO3BwoY2MiqFDt3IN+nivEV+38XKGzjgMxk4ky6plag5u35dkwbFY=,iv:z2HU58fBxJOzxQp/MHXVFEsupJCV5FoI7C4O5d4TXec=,tag:Zv184rX/3V0uJ8yJHBzhrg==,type:comment]
    #ENC[AES256_GCM,data:xikhLOQv/2NJc+P/QRvL2wpTYFPPWGJ7NVKFVg9ZjM04PdlijMtmY9qqw9GPRWgYKnF+d+DT,iv:r7aGwYYetCo1va8qPK+LytkRTJRRNeNF1CTEdCZxxA0=,tag:LRSslpl548caLB5d50o+RQ==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:geAdE6I5ZwSXKeLcs9Cr1g==,iv:Hp4zddF8bx5E+mlu5/YLO4L61gzeD4fi7MxbdnGAvmU=,tag:YuhM90xjySzo+3uMEBPOoA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:bicJ6Z1zltlJGD47GqesjQ==,iv:etBmt+9prcQpb0YnXUo890asioJKxefknkfRT/JpRuY=,tag:cbe4g3zfe3csSOgODacIRg==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:RmuaoITe/p7/iHynZd9mPuEkcF8Oxi9AGdDw1LzqnY12WP624oqJQQ==,iv:cntfy2n+f6YZnhpcUmm7NmfSGysc3gnpHUA1md37L8c=,tag:orah+KEtnNBsKpineNXPzg==,type:str]
    #ENC[AES256_GCM,data:yoYI++Ia1jVBlSahHfbaIjzONqtazlWodcO89OdCjdNu4xtjB8KGQB7VoG5UXCyMYg/yYUv4Ok4=,iv:TQHJz1kZwocBaqofzjH1f9aadBU1oWDr+5u0VQAhr8k=,tag:yG2wGD8ljupHYkS4LZzyNQ==,type:comment]
    #ENC[AES256_GCM,data:9b5bdqIkqw3CKZv8xT4et29DDjZboPer3Q==,iv:yqLsxiVN8coj1vDKDKsj49rxu7ETdDMXX8JbQ9Ln2bc=,tag:vRcuIqfhbGLghvIhgejQ8A==,type:comment]
    #ENC[AES256_GCM,data:jXVClxIoxpodGyUss/ZjiBOxEJ6N2qB42j0ET/TLONZM8vLPmKmVhx14F53gWTbWr7ETQZxDVHCU3IwiybUJdn2KJp55yRE/fwNBWmc=,iv:5SQwszDKAMYLmL0fnXK7znHvy9mcVI1nCMOWwEVfzt8=,tag:+i/PHXRgxlah8Ra6Z2d4sA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:ChWEuKvV97drshYIjVnRK/vyHFpZvN721WtohqbKMFouuP7saA==,iv:Iv3HiNAzlG1c7mHlMCutiXh6nMqqkBTPwMLXg+8e50I=,tag:QpdgN+aoo82fIAUnfKMPoA==,type:str]
    #ENC[AES256_GCM,data:0z6q9fhv9ySpM2L/LaoQIQ4N9EO7GbFPkDHIFQlvAnU6r/4Y6frNJw6jPuElgTEFLyBXAe4zludoMrlyWWB7wIB2HmrEk4M=,iv:z7nGTrOhOwtyoz5gzbPa8GtmcQPjJgrr1k6a3KzrPCY=,tag:Ohr3T/P/KbnJW95hK8h0Dw==,type:comment]
    #ENC[AES256_GCM,data:0P5sVsLqA1r1+cdfQcB/Pu3B178x4dCeVpzAG5rSp4zhsRcvVdwFbvVqfb98HSKbvMWqj2k9,iv:oHTg+du3NdSduX3T7EwPLPGS1huBSWxeaPbkLhjinRA=,tag:50CjXIBNrEgLs/wDtKG6qQ==,type:comment]
    #ENC[AES256_GCM,data:5GGk/uveiDILPxxXZlVJICtuSQi/tpiVGhOggVWNiYwfoNM=,iv:R5mn0sJrP02QshoVicLzdCYJ+254Ao3LD2EESvtsPAU=,tag:FAZbMITaZARfYMTGV3stFQ==,type:comment]
    #ENC[AES256_GCM,data:YAfpEPVkhiWXh8mrYC4l1ij2/pW/k4G5FKO6WCUS+QDkYyQlKnXi,iv:MdL11kR3dD1J0/KBXAAJsqTzAnKUCFNU0/INz9BtNBI=,tag:bWS5UGCd3hbATWkP0HMWGw==,type:comment]
    #ENC[AES256_GCM,data:36b8otwuiQggL4qsgwY=,iv:wsBLdGSwRAoOEFDiAKdx9zeu5TGBGcdg8a47JgMQg5I=,tag:ywJUAkGHavv5K0zXm8d/4g==,type:comment]
    PODNET: ENC[AES256_GCM,data:bjcN04oCg9gwhYKrig==,iv:b6Z6eSJ1H+OWHJnRXSQQpaogtlPzSpFfIfc9wcrhlP8=,tag:y6HJwcrk2VKWC3a+XT6cSA==,type:str]
    SVCNET: ENC[AES256_GCM,data:RlmlqKvG4cSyqIrIow==,iv:CZSsvnYXdbaYsDfgXdxAVHt523UZryb/eJrDAxrn0EA=,tag:onMwAM8vPYU7jC/bI0SPhg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:vziGrw==,iv:0KCSLvpmlqbA/h+5/+ACyVXa0zh1LaHlb6stmAK5rD8=,tag:zJnyXiPifcdaCPEvtjLKGg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zq9rvzhq3suqyxfpr25ak582jyzvv4r6ahlxry0l24k4f7mp655qm5cuk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRVo1SGw1RDNoSFJiVWxF
            ODliTk14SGY2MXZWOC95ZkZ3TUtaMGZhRUNvCitxa2pYN0lrd2lKZGlNTTE3WmJP
            UHlWM3lNNFg2elNPT1Y1VnB0WFQzNkkKLS0tIERMMEJ3ZWdqQVVpSS9qNXViZ2hD
            T3IvSFloVmJWZUw3U0JKamZ6L2xwcU0KJem1069SwMnqqGZ3Ewdz5jN2ZtEGnb/t
            j+YmMuqEnQBZKBn8FpIlrm1VnA9W79c7dn7/di0/5KJo7609ORmFwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T12:29:27Z"
    mac: ENC[AES256_GCM,data:+naE7iwy7U4K0tYOhxsWQ93NYn/nQpUVZfOlfSHYkMpoV6HWgf1sAV2OsP0EJAg1ObtKt+ZkdEJbUCRMS9wM5GKQm3FyIfmb6tLBFGTFPGzzYhN2xgmKPEK2VM0WXsYyMhBev09xd7pHALUdaZpeUJpkhAGltTGx+X/8yBgw9Wk=,iv:10fjTLSMq/M2FtzTp0IaNFMhsbxK7cGnzFJHHT4DpB0=,tag:gO9Ag7jSQFWeBYOmJ2j29A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
