apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:js4U9xjvMzntI9fckPNrFHymcY0xpGBaZPj+/gPiKlPNfGaZN24r3AXHlvHouuuOTvlMvIldwkdFWjuQnsrLHP26Hkdn9IZyzD7Ns5MZ9qMFJisLByo6MSSdrAXmbQLB3BvkTgxatgpoNYtERyaTNjPdLP/TbDn17Tlnsv0T6W+uuWSmJ7JLOosbiU8ET8Wu0T4bz9Woa2+Ti+jQxpB/0FtZgxL9LtxpgNkWXKa6Tt/XzYiYo8yTQ8PEwpeUvtXze2g/1UqatdbeEjNQuRh8pUc9RDHIXFq7y3FdIX37IG1DOeA2BgY2qLu56KRARRxBGZ1eCGnu6o13+gUsUlaLjMnGTKV0jRCnws0j/qHNg4WaLq2gMPOo+pPVHVU1COP4,iv:hmew5qgEx0FqJC80GOQA3fETXqJoAvss2KMZGKdKIfM=,tag:XCo6JZGzQDQagUxFQs2fNg==,type:str]
    identity.pub: ENC[AES256_GCM,data:iP2CCGae4YWLuPFZlCzYCXjScgub817MkKN2WzMCV34lck6o3dHCTI/Yt5/CQc7iXBxDtG8iGjqOIMz50Hifwzn3GsDidJVKLP9sG7PhOL+BmqQkomQNSTTnaqDTSyXSjHElfRgaS3Iw/R5n8nbSxZvcwXfx70oHi2dDcXy1p7Eq9BhadB3sMyWEeksI7W+RAvzc+OIqayEqJ6I7dQgX0Qp8KJzqZT5qPpvSwfx5UhAF6Ngd4asDw0iI6t6KrQa+3vfs2ZJ9tCjX7qXjzg==,iv:TVaF0FY2yirjmbQy9qoS6Njy7dwoniLxodhAdQSXoss=,tag:O9rkVPsaQHMPOl8lYDsjrw==,type:str]
    known_hosts: ENC[AES256_GCM,data:WUISVXv2bbs0OLmTb9rvqPJ6nfXoTQvyXvIsio5ayepKq3+zIc97vIuUFH5h7MSiW1T87fSrZTHMUdkda+HMoKg+bw086KYpTsM/Wl378kNF1Jg1CqEuIzvZG6f04XxCWzdQv/noGAYas8YcbMLd8qs8B1WYqrgJSgOjh/5IBjSMlUIfb4u7vmfWTMIphySRbLk09Abz2e1l9KIgwouscz17csxsso4KpE5D,iv:iy3Q5X9rFN89NumxBPuV+rzDvj7rpJp7nGuJYAa4yIo=,tag:kGdeKB1ss8I53lVopD4mAA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zq9rvzhq3suqyxfpr25ak582jyzvv4r6ahlxry0l24k4f7mp655qm5cuk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTDJ2Mms3VWUvcWVPZ2hC
            VzR6a1Bka2F5VEEzQmh1M2l0NW9pT3VGNUdFClRibnJSL1A3bE50MnJKU1dJcm1j
            YUJ3d2ZCdGp1Tmphb0tYeU4vdDlRbzAKLS0tIHdxK2gwZmFjWDhQSDNPNGRrWE9K
            VGlDRHU0b05jajFlYVU5My91TjlHcEUK0o/JfYJbADEAerovtwqVQ3jr7lbOzrK6
            zgA1wtTHA7T+WfDXmEUQnqnDoOlmaQWVHxhtAX2rSRc5pyr58ZRuow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-18T11:55:52Z"
    mac: ENC[AES256_GCM,data:OW1tOhaSFRxnYKt+LtC791A0t+MjccIvW1xmTD7hQl2cKnwJDy35hqmcvqYmTmUK1+W09OvPHwpHEhhJa0hS6g/BX0SCS5mZQ+WWfxw5p0lP0ABb+0HFm8zWqbRjOTSqKYnQ1SaesM4KOdbE8SvK1/4IaOCJ90BcDuLzTdnbkug=,iv:Jv9Tce5pAEpCEWFn4JGXC+AlFSTA4WkGMqLvZAFuUOI=,tag:9s+axyzxYsfJEdQkqieoaw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
