apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.x
    helm:
      releaseName: sealed-secrets
      parameters:
      - name: fullnameOverride
        value: sealed-secrets-controller
  destination:
    server: "https://struppi.effeffcee.de:6443"
    namespace: kube-system
