apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Wp8G72urlTYKkFoLVKp/iahdasq18RvZWY3nxuvvfIc+KAaXJ+YoMh7oAWsGSOGf2ic6JZYMLfHdvMNKRA4FbPc=,iv:949bcYPp5H1Satv0IHWYuW5sL4toegpACofd7qTfgK8=,tag:TbUgH5ayWimuX/oa9s45bw==,type:comment]
    #ENC[AES256_GCM,data:fXL41IgNZ/PaMSM7s9ZGwlWNcK6YB5ryV8Rtk+B2b/XrQyYKaKIvAPP/Eus=,iv:wahC/voLQQm59xZ/gwm2qT2HnZEqsA7YvvSKw9vDyfI=,tag:pRmg1bBpaKa6+p/HZWDxgg==,type:comment]
    VIP: ENC[AES256_GCM,data:bN2bH0ehxR7NZh6/GcY=,iv:D4tXtPRjfIlmZhxEMN1/UoF3DNda0euQyZobyAWO3Dk=,tag:7d+x4cJylvbFiTgi8Vm4ZA==,type:str]
    #ENC[AES256_GCM,data:QS3tby1NZYdUqB2NY/kzDe12CQpiuiAsBY5o,iv:cHzYnDMUoc9DgSVH6H4knl4BetVvdFl5FRzJCLP5JoU=,tag:HbRdYoO6SOT0Jtdw0j1fMA==,type:comment]
    #ENC[AES256_GCM,data:9FbcbT2dX6IYXUikuXYNYe45U+5Iv9C0O1ntlmXu6Hf4A6xl6XGacDkovYMOo+cdRhjH/4aaDwg4PX6j4M4a8F1JLPz3LtXt9VGGYSZVmk/bHb1mI0eCIc0=,iv:toKzjEvGpnMgeHCtu7IgGSJiwU2ePJR4EobmZ7qKNo0=,tag:E4nc1GBX/BSEFei2Kh+O9Q==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:2O/82c3cBn8YenilwLI=,iv:xgTVb+Vb6HO57N8ZBkJMYkwJ4jCfxJIptCzJXkX4pig=,tag:etrMCzh+CUDOftKxuARCgA==,type:str]
    #ENC[AES256_GCM,data:vyw1mEnvwXYWAXtuQEjf0nydPP3cvIVb4eDyupGm/qPqcA==,iv:gUYYOw/hQXE1zkgK+CYVog5BLQu/0PGVPbCzBd+KyfA=,tag:yejftA8usSdjpdyStY5lYQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:MjoBX+K5vUTQitFj,iv:aAFmxz6fWPFf5ORvGuCScvoOf7t4rmYpOL+U3kE+Uyk=,tag:dwAfRZvEjQ911cCJ4V25Uw==,type:str]
    #ENC[AES256_GCM,data:0qedxmg6zy65Td3lRWsQi5eWWCZC6o0tTjouo84foA8/6H1qSysBMpxJZujY8es=,iv:kHWNAvBlx+p+0rzuccNK7xrl8tDpPskHgKr+A4pYZRY=,tag:uyTbFHiAX5YTr9E/kwiECg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:K9kjT/ifSV9+REWyklgmyDR05altW7Br26xU30Q=,iv:hvyqVVbnQk2hApgdzMrW310ooOKlQF24rbj6jJg5e/8=,tag:5NjbX8zzktZyfWhXggLROw==,type:str]
    #ENC[AES256_GCM,data:+Xj29ogpFo91jROVtGmLAwbtEB4EVX+mrhQUnDVTnsdlySRDRu0GEKgVTv91HCNTLaDJbBOvH8Qqg0LW2+qihsDDbhxst62CVbouXKIz+lIkow==,iv:WPw6UvJWOtcLCLjdEN7hwwraE3nITuXWDfwP/bFpVpw=,tag:+UrAu2jVyGS3viNR7MksGg==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:5Aa6qOMUzmlRiDwBGxM=,iv:l1fCIGh5r+rCcvhVIALRoGwOihCwqHme9tLOaD+r9xM=,tag:5m9B148q+buIUF06EVXsQA==,type:str]
    #ENC[AES256_GCM,data:71qZZqqGxHetstN0aFlyjoGgsob1lM1kl3iZV6aKhCYV,iv:qMkmXjM3z1b7ZsUBThQukxl9KvLE/L8oOhsP5NvBD00=,tag:59i6ooUt0D3tIEb2IQ18/w==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:alDbmr5kMn/KyK5OWlw=,iv:CNC9ijXDuMmAoG6EDsdQ7NunAvkVEN4Ztedv0KkPUKs=,tag:u5YM5BWS2oOhnQlmn8i8sw==,type:str]
    #ENC[AES256_GCM,data:r17LsyQOg/FHalCi4vbu4T9cYSz6JQWpYa34HIlwoXoi9lW+y3vJTMWkaKU4yBBmZ3GmsyqEzmD0KRw/PaJ8MaQCu82ltREggoWJVMVynbQ=,iv:g93SzvxNYv0oxMDFdW1TuE7A5AVgjVJDHMFohN+6xhA=,tag:Wza1X4MLhlFbMnHzcAhOVg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:dQTNr4k8NX+u6quGx6I=,iv:JXWQLbx5qs3Y7L+pGvHskNusYueicwXvIg0HhP3UVOY=,tag:CuwT6bnjSf1DIE61yNCyow==,type:str]
    #ENC[AES256_GCM,data:C17YT5P2aUFgOcCSOJ/dgW0FRCThh38sMIQsMFD0STRaix0BH2Fb9YuN5BhVUQygn0HIxRSTnwKq/smMRdQ4OLZbu3OV1lMhUzWelP0oyMGxoFzeoJIV,iv:MA1I/qZYn0hyv9VOvZkWi29wcAdnaMwPNOcnAKyB0L4=,tag:3Mjo7OSfECOK2xEapfW6ag==,type:comment]
    #ENC[AES256_GCM,data:/pn9WXwnTqnaaboa0Q4uoHa670KZyeCWBfDcCgrkk3ANCGy01Gys3LQXYNM9/rWRfwfj5iIx1DVxQqtJisQwYNuDjRYKJMr9ax4P4JlMlaRuK23Ow6k5DFwY0Ss9OWepboZJ10dUhHkb1Q1yhzkuw29gE8oxglzkw6oUHw==,iv:5CmFv1ErnyAm5cRPgnHPb823uOAADH+qvLoa/yknhVY=,tag:13WTzGaI3AMSReIFO36VSw==,type:comment]
    #ENC[AES256_GCM,data:adN/VrlGUioVO+/0WkhzZ7koe3ZgOMyAq9V8BiCNFZEgRFuybzGPD0TLbsjYVgq4E0mvxEbY0l/qUMqZUNccfojyxnEB8mkr6YPHzAu8rXw=,iv:w1o1ob2kjva8NUawMDE4L+anessVYx7iUMhbYimRZhE=,tag:7cLKx9vqM7l/fRb09t0Deg==,type:comment]
    #ENC[AES256_GCM,data:EIjclWitoBBXfE5Onhx0eglMYCgaus1EF8/HXGBm9p1lyR66Re65p8ur+6Dari2ET3KpZLhy,iv:Z9GriBgeXGojuim88l9FZlGYfB8L5XJTeKl8uTbpUR8=,tag:+IJxDgs6zXHWjPl3QiIamQ==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:xkIUjDrMO6rqvPo/irAZew==,iv:T5+RUR7QfunGzeC+yOiXxTz1U/myZcqhWSODSPZFg40=,tag:vNqAYwGDO34Er2mTaWaiiA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:GHkyLwixmEGjRXYhcXLRkw==,iv:gQUe3TWHMDQGfNyhoJZBvvgSSuAot0gsjcYHPxUVbXY=,tag:iTA4gz943Ck9Dy+0+fIeLw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:z9l2zIjV1tcMsuWEOODyzyzLEMBmHiCaB8I1qQawlh/FTQGkS6MMsg==,iv:VsPJC3uuVHAp5ODGxaM2jlw5CqpfAynb/SqP0JAy09Y=,tag:R90ZqH5J4CP9vQAOxzvxvA==,type:str]
    #ENC[AES256_GCM,data:/Nyn4LTnhBaFIeJR1x35OpnPCkmzxAIuCpHwhIKLihYdtgN6bIjalrKxxyYR/M0yzAi2+wKIlvc=,iv:B5Qq4/kyx9tJT81I4hybFGcYlcQlcZjmky5cuI17LrI=,tag:qJS5TMbQuipTgO4b+gguRw==,type:comment]
    #ENC[AES256_GCM,data:FG4JMkCQpKLApG2DfeK6e3dccIOR/m2mNA==,iv:D8kvrJ+WPXbp0mfMGxtGKMzkz37SCl8+7tZnHQHUqI4=,tag:AL3sA29MvUzzxJLNz3AYLw==,type:comment]
    #ENC[AES256_GCM,data:cirov/0poc4eFXxtI4PRO//KlHNMuET0sCvzDMOjVBH5KRFQFQqqgpHkwsRr4Ps+V/Am+dsC+Z8pgx6WALUG4SnJZQ/747/jjVukulc=,iv:iQPC6M+QPpKZuq5MRCmw5klKa5Fu7uPJsXKpacKpBFw=,tag:ZkzVtqPyvSkO2KKk0AvZ3A==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:BR6VPdhRG5j+J80GgSWxwQ1A9gabYQvjYgRqEgPaNPnymqzW7w==,iv:qJxQsUrfDIWddIH5q0XQfAfeAtK6xoV8A8GkZ6Oamy4=,tag:Qv52mqMXnmN7O4us/fCu5Q==,type:str]
    #ENC[AES256_GCM,data:aGFCTNWcP3qU9u1Cwlrgh+vA9C38qAYvfbV/tNta7qoNybXIpNdoABAllS5M7QLfcNihiduuT23c2wIagQugkoH30JQuqNk=,iv:SV7VqzEvvZFVMVAOQQP5u3n7ABGN/G2PiiyYzuad3KA=,tag:vtoijhtjy91/Ugr2XLfhag==,type:comment]
    #ENC[AES256_GCM,data:Yy/ZN4K46lTmNiiIn/n3g4w7QgJxtikU50GLT7Mso+cCJmgptmDHJdg039u8yhKGpWK9UkyE,iv:UBJDMwz1TtzbSK9HrWUEvN2Gs+cPfe0Jefx4VEfuWzo=,tag:CvnYS8tPJANG0bHjDAFFFw==,type:comment]
    #ENC[AES256_GCM,data:s5kUuipk6KQ0boeuzekkPAR0HBUIFacJTZHMQmFCDonIVDI=,iv:jw8G2Rraw+zSQ7UUTo7bH8wGPlsRzRcfMaO/kiz1eWw=,tag:sWvaJquaW2w/5S6tEYs8nw==,type:comment]
    #ENC[AES256_GCM,data:hxaGi81CDibPtGd8EjvDJ6e7VePdQGg2mnYgmpuiCHK66z3b7nBx,iv:Wv4NATKUnLgCP6mlx4WgwvrAT20gEU8h+68n4MLdNyo=,tag:PUBE0kNJ8gKj8iNmjY56wg==,type:comment]
    #ENC[AES256_GCM,data:RHAzuuVuLHeScyweXvQ=,iv:RzQ+FQayTNFB1dwCTozsKmDYhrYZLtXmCRCsRudSn8Y=,tag:FAHEkpnuSaOmdae6HkOJOg==,type:comment]
    PODNET: ENC[AES256_GCM,data:b+tlsSyIp9GMHb4Vog==,iv:nyOQTF2EM1bqkVoJSzpa84+bjAJDjifYn7WYOvIgXik=,tag:W2MNaT3zX5UACdaf1/SAsA==,type:str]
    SVCNET: ENC[AES256_GCM,data:BNBe6S+FPf4ji7JvqA==,iv:2FeHAzt1rkSNHu8IuQao5ReptQfWqiwlmDm0oylMMAM=,tag:GWV7BCuwMtHQXdKdhnDm9Q==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:eadugzsM97M=,iv:bCUhe9WM2X95WPIoJfY7zTClC+wqXVakG1RglDA5IKs=,tag:61QHZoDrSfTp3nCitRbVhg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zq9rvzhq3suqyxfpr25ak582jyzvv4r6ahlxry0l24k4f7mp655qm5cuk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRGhWa3lObEswNXRDeFM4
            L0xiK21xUkhnSWxta3FoT0xQRlFTZmZxYjBJCk1oUUV2RStqeEdneEVVR1ZWbnJK
            cWhPY0JRcEpwUW5rcTA5Z1IxeHNEcW8KLS0tIDQrU2xIT1JaRGxjTjhrTmJlWUpR
            SElRWjJDcVF3Y1dCQUZJSzIyS1RIeUkKZ2YVFMVCoxXEYBa4B9cczwi7xE5kQBih
            +cktZjiBAfu10R/XOcS6GT1NTZzMN+FXWLZw9JWuP+gcsTOV5Gyb+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T16:01:44Z"
    mac: ENC[AES256_GCM,data:Ur1j4uimy98MML0mbldvuIeGMOOB3UJPfJZ5TmLGr0EeoXIPNTB3zdQXDm0UXuac2yrQf6tKky13+hsnb370GE0xxM8zSSk0qtH0S0VDv5Isb0f0481QnyLaoENbRIH5XVxkv/8w+SrFDDtHCIKFgA2u5+HD2T4Hp15JNVvGiZI=,iv:wuQLsbvD4lpg9KY8DLgERCg3co+L7YcaLNBucOMS9VU=,tag:6j+fuGikFKE6zN+LQ+ihZA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
