apiVersion: v1
data:
    TOKEN: ENC[AES256_GCM,data:xVaLbsgUwTJpGxWcaG4cwKvO0IYkrdMG8zOj5yoZSR8P6TYgrw+Pm25WBh8=,iv:ANB/R3/NjJL79sFOkKoLd55+thrcBoirHSQbF+/kIhY=,tag:7qV4GsEcOB9S1F9ZOgmH1g==,type:str]
kind: Secret
metadata:
    namespace: home-assistant
    name: home-assistant-tunnel-token
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zq9rvzhq3suqyxfpr25ak582jyzvv4r6ahlxry0l24k4f7mp655qm5cuk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTzFIRlpBUzdXVXNQZmc1
            ZXcvM09TakhvVEQxN3NaU0UySFc2OThIN1FJCjM0YUkvVkpBL0NWcnFKeTAxeHRW
            d2F4c3pxWlZsV0o1S250UUs2YXBrYUEKLS0tIHZDQUdKZGw5aDhsMzE4MmFpNDRY
            NzRVWC9wUElVTkEzZEtOODJvYTZNM3cKAi8ng0ygdJwo7vj30At3ndCm9arlfPMK
            GFZNarhY/GkQP9d8tVVd1frgH8Og1/2uSbrTXLQQp0hpFBKKTerAIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T13:10:22Z"
    mac: ENC[AES256_GCM,data:Fks0+3qUlAVGr2YDeja454xw5SDJ4MD1VYFIRa9QEsM/Ek86d24t45yhpCIBVuJBrSxobHLeEOD212EW0pQL/QD17JOXgXX2TPVw+7gP8EGJ42U4brgFCkPnNabtOn8JLtwsyRBrx2jIuOu9IhJNwqzckKMMtmWA4ChgfjsiIcg=,iv:03TXkj2OZk9cPctHe5WDyyy9UOPMX2MvAWVWSU8cfsE=,tag:EEsyFt54A6ukhqHhTqDOeQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(token))
    version: 3.9.1
