apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=false
spec:
  project: default
  sources:
  - chart: home-assistant
    repoURL: 'tccr.io/truecharts'
    targetRevision: 26.8.5
    helm:
      skipTests: true
      values: |
        TZ: Europe/Berlin
        global:
          fallbackDefaults:
            pvcSize: 1G
            vctSize: 1G
        # service:
        #   main:
        #     externalTrafficPolicy: Local
        #     loadBalancerIP: ${HOME_ASSISTANT_IP}
        #     type: LoadBalancer

        ingress:
          main:
            enabled: true
            hosts:
            - host: smarthome.leiderfischer.de
              paths:
              - path: /
                pathType: Prefix
            tls: []
            integrations:
              traefik:
                enabled: true
  - repoURL: https://github.com/svenihoney/k8s.git
    path: clusters/main/kubernetes-argo/apps/home-assistant/app
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: home-assistant
