apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: weave-gitops
    namespace: kube-system
    # annotations:
    #     meta.helm.sh/release-name: weave-gitops
    #     meta.helm.sh/release-namespace: kube-system
    # labels:
    #     app.kubernetes.io/managed-by: Helm
spec:
    interval: 15m
    chart:
        spec:
            chart: weave-gitops
            # version: 0.1.0
            sourceRef:
                kind: HelmRepository
                name: weave-gitops
                namespace: flux-system
            interval: 15m
    values:
        WEAVE_GITOPS_FEATURE_TELEMETRY: "false"
        adminUser:
            create: true
            passwordHash: $2a$10$6DJwOqyUobQm7O7b97bwsOp.4ZwTs7bgNJ3L8smfKjJv/xNh44BYi
            username: admin
