apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: party100
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/external/kubernetes/apps/party100/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

