apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tandoor
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/external/kubernetes/apps/tandoor/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

