---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 15m
  chart:
    spec:
      chart: minio
      version: 13.10.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      fallbackDefaults:
        pvcSize: 50G
        vctSize: 50G
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                MINIO_BROWSER_REDIRECT_URL: "https://minio.leiderfischer.de"
                # MINIO_SERVER_URL: "https://minio.leiderfischer.de"
    persistence:
      config:
        size: 50Gi
    ingress:
      main:
        enabled: true
        hosts:
        - host: minio.leiderfischer.de
          paths:
          - path: /
            pathType: Prefix
        tls: []
      api:
        enabled: true
        hosts:
        - host: s3.leiderfischer.de
          paths:
          - path: /
            pathType: Prefix
        tls: []
