---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-dns-staging
    namespace: clusterissuer
spec:
    acme:
        # You must replace this email address with your own.
        # Let's Encrypt will use this to contact you about expiring
        # certificates, and issues related to your account.
        email: letsencrypt@effeffcee.de
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            # Secret resource that will be used to store the account's private key.
            name: issuer-account-key-dns-staging
        # Add a single challenge solver, HTTP01 using nginx
        solvers:
            - dns01:
                webhook:
                    groupName: com.netcup.webhook
                    solverName: netcup
                    config:
                        secretRef: netcup-api
                        secretNamespace: clusterissuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-dns-prod
    namespace: clusterissuer
spec:
    acme:
        # You must replace this email address with your own.
        # Let's Encrypt will use this to contact you about expiring
        # certificates, and issues related to your account.
        email: letsencrypt@effeffcee.de
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            # Secret resource that will be used to store the account's private key.
            name: issuer-account-key-dns-prod
        # Add a single challenge solver, HTTP01 using nginx
        solvers:
            - dns01:
                webhook:
                    groupName: com.netcup.webhook
                    solverName: netcup
                    config:
                        secretRef: netcup-api
                        secretNamespace: clusterissuer
