---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: effeffcee-de
    namespace: clusterissuer
spec:
    dnsNames:
        - '*.effeffcee.de'
    issuerRef:
        kind: ClusterIssuer
        name: letsencrypt-dns-prod
    secretName: effeffcee-de-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: leiderfischer-de
    namespace: clusterissuer
spec:
    dnsNames:
        - '*.leiderfischer.de'
    issuerRef:
        kind: ClusterIssuer
        name: letsencrypt-dns-prod
    secretName: leiderfischer-de-tls
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
    name: default # Only the store with the name default is taken into account
    namespace: clusterissuer
spec:
    certificates:
        - secretName: effeffcee-de-tls
    defaultCertificate:
        secretName: leiderfischer-de-tls
