---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: effeffcee-de
    namespace: clusterissuer
spec:
    dnsNames:
        - '*.effeffcee.de'
    issuerRef:
        kind: ClusterIssuer
        name: letsencrypt-dns-prod
    secretName: effeffcee-de-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: leiderfischer-de
    namespace: clusterissuer
spec:
    dnsNames:
        - '*.leiderfischer.de'
    issuerRef:
        kind: ClusterIssuer
        name: letsencrypt-dns-prod
    secretName: leiderfischer-de-tls
