apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cert-manager-webhook-netcup
    namespace: clusterissuer
spec:
    interval: 5m
    chart:
        spec:
            chart: cert-manager-webhook-netcup
            version: ">=1.0.25"
            sourceRef:
                kind: HelmRepository
                name: aellwein
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
        certManager:
            serviceAccountName: cert-manager-certmanager
