apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/svenihoney/k8s.git
    path: clusters/main/kubernetes-argo/argocd
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: home-assistant
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/hostUsers
    - group: postgresql.cnpg.io
      kind: "*"
      jqPathExpressions:
        - .spec.resources.limits.cpu
