apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # Enable helm for kustomize
  kustomize.buildOptions: "--enable-helm"
  resource.exclusions: |
    - apiGroups:
      - "cilium.io" # no /v2 suffix or similar here...
      kinds:
      - "CiliumIdentity"
      clusters:
      - "*"
