apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: home-assistant
    namespace: home-assistant
spec:
    interval: 15m
    chart:
        spec:
            chart: home-assistant
            version: '>=26.8.2'
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: Europe/Berlin
        global:
            fallbackDefaults:
                pvcSize: 1Gi
                vctSize: 1Gi
        credentials:
            extminio:
                type: s3
                # url: https://s3.eu-central-003.backblazeb2.com
                url: https://s3.leiderfischer.de
                bucket: volsync
                accessKey: ENC[AES256_GCM,data:lEB5n9MMsj8WDn6QB6O2brvELMk=,iv:faX8PL0yCV9g7N59nuZW/RtVYF7ZvVrsti/je13P56s=,tag:lK9YF2NN3R6o7lLzFAKvjg==,type:str]
                secretKey: ENC[AES256_GCM,data:Yn+DoCs1KlU53aToEYCsJ6nmgQWL3hG6yfsbB2jgbqAald/fA7lGPw==,iv:4A2jQ+v0ELoB8pHp03uuD9ZoJHOIYwHFBl6BeNYh9k0=,tag:+vcnOSR8JRjWYcIyfRJ2bg==,type:str]
                encrKey: ENC[AES256_GCM,data:BLGq24REw0b+1yWr8yx3xh3qLpCymaVfiN+2I+LY8mopS0ZsywR7J5DldV6xO6LD8QICVjnEMVF8JdcYg8hurQ==,iv:j+NZRixS/72YNd6CGH7qXITN+82G+O8HtvyewnaU5YY=,tag:KJre/EIFSm4ThzdvnCFUkw==,type:str]
        # service:
        #   main:
        #     externalTrafficPolicy: Local
        #     loadBalancerIP: ${HOME_ASSISTANT_IP}
        #     type: LoadBalancer
        # podOptions:
        #   hostNetwork: true
        workload:
            main:
                podSpec:
                annotations:
                    k8s.v1.cni.cncf.io/networks: macvlan-conf
        configmap:
            init:
                enabled: true
                data:
                    #ENC[AES256_GCM,data:71buJ4NVXJZyK4s6wEE+Q0O2cd9Z,iv:Uh7gjdqPseLZ2tdVS0L79mabJHlw0D7BFaM27G9UV0o=,tag:I9RZNtcdHPJal3UU7af1xQ==,type:comment]
                    #ENC[AES256_GCM,data:HSRRZ5zAZ8p/PY86,iv:bO1ImJKdXaxLPOdeP89ZgHvoO+PdTYlMdE7x8+wGE3E=,tag:xPlAxoFAYME4TbBr8BZVog==,type:comment]
                    http.default: ENC[AES256_GCM,data:AX9yT+YOReK+FOqwNnQrtSJohyJCKA/Sbij4/gqVcJ+/02r+IwK+x9bljBhUcfVxFtAXVwEqT8u4AtVmvYtrY8DUPng=,iv:akVjQHwScGij9f3CNJb2mL+HsNqDbuXwNrRPQfzDd+I=,tag:oRyvEuQGXJrCvA/JYmHFYg==,type:str]
        cnpg:
            main:
                cluster:
                    instances: 1
                    singleNode: true
                    storage:
                        size: 10Gi
                    walStorage:
                        size: 2Gi
                # mode: recovery
                backups:
                    enabled: true
                    credentials: extminio
                recovery:
                    credentials: extminio
        ingress:
            main:
                enabled: true
                hosts:
                    - host: smarthome.leiderfischer.de
                      paths:
                        - path: /
                          pathType: Prefix
                # integrations:
                #   certManager:
                #     enabled: false
                #   homepage:
                #     enabled: false
                #   traefik:
                #     allowCors: false
                #     enabled: true
                #     entrypoints:
                #     - websecure
                #     middlewares: []
                tls: []
        persistence:
            config:
                volsync:
                    - name: config
                      trigger:
                        schedule: 0 0 * * *
                      ## TODO: other options
                      type: restic
                      credentials: extminio
                      dest:
                        enabled: true
                      src:
                        enabled: true
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zq9rvzhq3suqyxfpr25ak582jyzvv4r6ahlxry0l24k4f7mp655qm5cuk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMlR5UjdURFZPL1ZJQ2Uw
            a1huZGhaWEVvTUVicmp2TllUVkZlSU9Zd1NNClZxK3VTT2tJU1J0NkhGbUpnTFB0
            TjFWYjFNZ3JZNEpUZ01FN0NHOGloUHcKLS0tIFY2R0lYNlBHdTRMN3c1Nk1BRHFJ
            eFdSeGJGSGo2cUQ5eUh0aFVpWFhIZXcKZphBdyDSNRFyuoWhq9xbHEbIQ+tbu0B0
            SF7onPR8F1CbiSo9W6eYW0FqWMosI01P9RjWaNjHPgJwtMEvc8uoDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T00:58:47Z"
    mac: ENC[AES256_GCM,data:pm8ASS9xMjZhaeZJ5YJeWDpyISOo/1qhD3M56L1RaLMCjz1w3ZknxaTnLQddW8SaumVK/JufjwFfxZUNNVDwcFs3AafUNrsEPgMM3tc6JRDi11ENwFiTDZorlr9muix2zGEstSH1vFWXrZNCqkKQSHTnoBOspDzF9V1GC6fIitI=,iv:33Ja1PgAxKC8udZP5pVErGtm5BSC7fKOV/JYCO9erGI=,tag:CTBJ4TRWo/1adMSUdLNBWA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: node-red
    namespace: home-assistant
spec:
    interval: 15m
    chart:
        spec:
            chart: node-red
            version: 21.1.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: Europe/Berlin
        global:
            fallbackDefaults:
                pvcSize: 1Gi
                vctSize: 1Gi
        credentials:
            extminio:
                type: s3
                # url: https://s3.eu-central-003.backblazeb2.com
                url: https://s3.leiderfischer.de
                bucket: volsync
                accessKey: ENC[AES256_GCM,data:Tntyyby7EfWfjk3VRy5HeQdWNK4=,iv:cuOoGP/q1R80LbynAPor2v/eNS7eeBqQngWd2Ap11AQ=,tag:wfkYDpPVH8nB7THBtxVPtA==,type:str]
                secretKey: ENC[AES256_GCM,data:f8f7+tJkuNhLtqr97vpIUSTjTkYe4NdKUqiPnmsK5GE017YPzULLzw==,iv:urPe0IcLM4uwqjoDcC+BIhXmDG8sIt+3nBzoBbV6DMk=,tag:cNQ+UC31b7gCJL72UY2ypA==,type:str]
                encrKey: ENC[AES256_GCM,data:5pJzvrSW4LWV5ktRdE9RdsRrff/rdA3EtiR8BdhgYTrq8Ui0sK5DKnvAQaEYk4HWKoQjEMYmP5N8Tr7NoJCEWA==,iv:ELo8esDWQA4IpeC+VRWTfujEFuZ7R8FyOnbc58duwJ0=,tag:fLEB3WU8tCQA18fgJBzlUg==,type:str]
        # service:
        #   main:
        #     externalTrafficPolicy: Local
        #     loadBalancerIP: ${HOME_ASSISTANT_IP}
        #     type: LoadBalancer
        ingress:
            main:
                enabled: true
                hosts:
                    - host: nodered.leiderfischer.de
                      paths:
                        - path: /
                          pathType: Prefix
                tls: []
        persistence:
            data:
                volsync:
                    - name: ENC[AES256_GCM,data:NCy8Zg==,iv:vBPSgDeCgu2ujxtOog4NDB2au4YEt8VBXmTRYgsD6yU=,tag:zEzvvwkSEB9zOeDMzi/Fbg==,type:str]
                      trigger:
                        schedule: ENC[AES256_GCM,data:mCZniOl4s2JR,iv:eq2L23qkY+9NRW37s44YlDpRykQjKh7G9PllMfQAzsM=,tag:FjekOUmo4OWcciaig/GRaA==,type:str]
                      #ENC[AES256_GCM,data:IY+eMM/z4tPgHyIHNx9AlRUn1ynq,iv:z83qRCBcjqVknMGZaFAtOR4qk7TpYCkIbAEVxKUi0Bo=,tag:6cSBqwm8w76pmjQlclHMfQ==,type:comment]
                      type: ENC[AES256_GCM,data:nzv9dzCp,iv:n6drkSR6YzEKeDA6vrVEBDJ7y4LOmPaKq5RUMhDlfY0=,tag:WxvhLbj3bQD5/fzKp1WIVw==,type:str]
                      credentials: ENC[AES256_GCM,data:vQQF+qN9J3k=,iv:fDMcG/a/b3VXhpQm6mdXzrtcnj9M5NUD8T8jCjT4xlY=,tag:a590GHMLePf37vf0f61iYw==,type:str]
                      dest:
                        enabled: ENC[AES256_GCM,data:M7QeQw==,iv:tH3MaSPAidOE8nyHuSsT4/7R06P+3CmVfhlITeQduRM=,tag:fFTSfHh+/z8JDA1CDLHSZA==,type:bool]
                      src:
                        enabled: ENC[AES256_GCM,data:XDwbiQ==,iv:vdLF9EaUrsYs6iXrQOvzuXZCUmM9EACAZLRHujnNFyI=,tag:JAam+uC+8ZIVVZn/JiKT0g==,type:bool]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zq9rvzhq3suqyxfpr25ak582jyzvv4r6ahlxry0l24k4f7mp655qm5cuk0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMlR5UjdURFZPL1ZJQ2Uw
            a1huZGhaWEVvTUVicmp2TllUVkZlSU9Zd1NNClZxK3VTT2tJU1J0NkhGbUpnTFB0
            TjFWYjFNZ3JZNEpUZ01FN0NHOGloUHcKLS0tIFY2R0lYNlBHdTRMN3c1Nk1BRHFJ
            eFdSeGJGSGo2cUQ5eUh0aFVpWFhIZXcKZphBdyDSNRFyuoWhq9xbHEbIQ+tbu0B0
            SF7onPR8F1CbiSo9W6eYW0FqWMosI01P9RjWaNjHPgJwtMEvc8uoDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T00:58:47Z"
    mac: ENC[AES256_GCM,data:pm8ASS9xMjZhaeZJ5YJeWDpyISOo/1qhD3M56L1RaLMCjz1w3ZknxaTnLQddW8SaumVK/JufjwFfxZUNNVDwcFs3AafUNrsEPgMM3tc6JRDi11ENwFiTDZorlr9muix2zGEstSH1vFWXrZNCqkKQSHTnoBOspDzF9V1GC6fIitI=,iv:33Ja1PgAxKC8udZP5pVErGtm5BSC7fKOV/JYCO9erGI=,tag:CTBJ4TRWo/1adMSUdLNBWA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
