apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - argocd-ingress.yaml
  - repositories.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    path: argocd-cmd-params-cm-patch.yaml
  - target:
      kind: ConfigMap
      name: argocd-cm
    path: argocd-cm-patch.yaml
