---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: party100
  namespace: party100
spec:
  interval: 15m
  chart:
    spec:
      chart: wordpress
      version: 9.14.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      fallbackDefaults:
        pvcSize: 1G
        vctSize: 1G
    wordpress:
      user: sven
      pass: unbekannt
      email: sven@leiderfischer.de
      first_name: Sven
      last_name: Fischer
      blog_name: Party 100
    ingress:
      main:
        enabled: true
        hosts:
        - host: party100.leiderfischer.de
          paths:
          - path: /
            pathType: Prefix
        tls: []
